Student workshop detail
Jahmilli/helps pull request #24
Opened 2019-10-06 10:38 UTC by KenPhetmany

I want to merge my current branch with Admin-workshop, so i'll know the workshop properties i'll be working with

2019-10-07 07:50 UTC, Jahmilli requested changes
good start, theres a few changes, the main one is around setting state which i'd recommend you have a look at.
Also is the StudentWorkshopDetails.tsx finished? lots of commented out stuff there.

2019-10-07 07:50 UTC, Jahmilli commented on src/components/presentational/StudentDashboard/StudentWorkshopDetails.tsx
> +	// }, [data]);
Do we need this here commented out?

2019-10-07 07:50 UTC, Jahmilli commented on src/components/presentational/StudentDashboard/StudentWorkshopDetails.tsx
> +		// </div>
Is this needed as well?

2019-10-07 07:50 UTC, Jahmilli commented on src/components/containers/StudentDashboard/StudentWorkshopRegistration.tsx
> +                workshopData = await getStudentWorkshops(context.userDetails.studentId);
don't do this. If we need to store state relevant to the component, use a state hook. 
See https://reactjs.org/docs/hooks-state.html
So what you could do (assuming your setState is called setWorkshopData) would be like:
 ```
let workshopData = await getStudentWorkshops(context.userDetails.studentId);
if (workshopData) {
  setWorkshopData(workshopData);
}
```
Also what is the type of workshop Data? You have `any`.

2019-10-07 07:50 UTC, Jahmilli commented on src/components/presentational/StudentDashboard/StudentWorkshopDetails.tsx
> +	const [state, setState] = React.useState({});
what is state being used here for?

2019-10-07 07:50 UTC, Jahmilli commented on src/components/presentational/StudentDashboard/StudentWorkshopDetails.tsx
> +	console.log('state from router is ', props.location.state);
Best not to keep console logs in unless for debugging purposes.

2019-10-10 06:53 UTC, luke9216 commented
Nope fuck off 😉

On Sun, 6 Oct. 2019, 9:38 pm KenPhetmany, <notifications@github.com> wrote:

> I want to merge my current branch with Admin-workshop, so i'll know the
> workshop properties i'll be working with
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Jahmilli/helps/pull/24
> Commit Summary
>
>    - Beginning Student Session
>    - Ken's addition to front end
>    - Ken - Added button to session details
>    - displays workshops
>    - navigates to details component
>    - passing state to student workshop details
>    - added extra properties to access workshop
>    - Merge branch 'admin-workshops' into student-workshop-detail
>
> File Changes
>
>    - *A*
>    src/components/containers/StudentDashboard/StudentWorkshopRegistration.tsx
>    <https://github.com/Jahmilli/helps/pull/24/files#diff-0> (51)
>    - *M* src/components/pages/StudentHomePage.tsx
>    <https://github.com/Jahmilli/helps/pull/24/files#diff-1> (6)
>    - *A*
>    src/components/presentational/StudentDashboard/StudentWorkshopDetails.tsx
>    <https://github.com/Jahmilli/helps/pull/24/files#diff-2> (57)
>    - *A* src/logic/functions/getStudentWorkshops.ts
>    <https://github.com/Jahmilli/helps/pull/24/files#diff-3> (7)
>    - *M* stubby/studentData/studentData.yml
>    <https://github.com/Jahmilli/helps/pull/24/files#diff-4> (10)
>    - *A* stubby/studentData/studentWorkshops.json
>    <https://github.com/Jahmilli/helps/pull/24/files#diff-5> (6)
>
> Patch Links:
>
>    - https://github.com/Jahmilli/helps/pull/24.patch
>    - https://github.com/Jahmilli/helps/pull/24.diff
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/Jahmilli/helps/pull/24?email_source=notifications&email_token=AHF53GN5DAVBI5HACCCFWZDQNHE4DA5CNFSM4I53NZUKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HP4NVAA>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHF53GP3DDLYPJR72GO3ACLQNHE4DANCNFSM4I53NZUA>
> .
>

2019-10-16 20:44 UTC, Jahmilli requested changes
it doesnt look like you've made the fixes i requested last week. You shouldnt be setting state in a component by directly assigning a new value. Use the state hook: https://reactjs.org/docs/hooks-state.html

2019-10-16 20:44 UTC, Jahmilli commented on src/components/containers/StudentDashboard/StudentWorkshopRegistration.tsx
> +	const [sessions, setSessions] = React.useState<Array<ISession>>([]);
this isn't being used?? 
Also should it be of type `Array<ISession>` or `Array<IWorkshop>`???

2019-10-16 20:44 UTC, Jahmilli commented on src/components/containers/StudentDashboard/StudentWorkshopRegistration.tsx
> +				workshopData = await getStudentWorkshops(context.userDetails.studentId);
you should do something like:
```
const workshopData = await getStudentWorkshops(context.userDetails.studentId);
 if (workshopData) {
  setSessions(workshopData);
}

```

2019-10-16 20:44 UTC, Jahmilli commented on src/components/pages/StudentHomePage.tsx
> +import { ISessionDetails } from '../../logic/domains/sessionDetails.domain';
Where is this being used?

2019-10-16 20:44 UTC, Jahmilli commented on src/components/presentational/StudentDashboard/StudentWorkshopDetails.tsx
> +	const [state, setState] = React.useState({});
??

2019-10-17 00:31 UTC, closed without merging

2019-10-17 00:31 UTC, KenPhetmany commented
Not needed anymore